### ISSUE TITLE
Can not open honor band 4   track files

### ISSUE THREAD

**Issue by fisherlong** [aricooperdavis/Huawei-TCX-Converter#15]
Hi there , I'm try to convert the track files from honor band 4 ,but it failed . Can you help me ?

![TIM截图20190624210642](https://user-images.githubusercontent.com/10540236/60021253-3f397f80-96c4-11e9-978c-371ddd209de2.jpg)

**Comment by aricooperdavis** [comment]
Sure, that error suggests that the timestamp at that particular entry is either 0 or negative. I can probably filter such entries out using the existing filtering mechanic. Could you attach your HiTrack file please? :-)

**Comment by CTHRU** [comment]
@fisherlong If you're still using the script, I'd like to inform if the issue is still there since the source code and handling of the Hitrack files has been ameliorated in the meantime. probably, your issue was related to pause records, but since we're not sure, it would be appreciated if you could give some feedback so this bug can be closed. Thank you.

**Comment by aricooperdavis** [comment]
Closed. Please re-open if the problem persists.
