### ISSUE TITLE
[insight] all data is available in clear json without root or huawei backup

### ISSUE THREAD

**Issue by dbdb** [aricooperdavis/Huawei-TCX-Converter#19]
Hi!
I found a way to export all data in json including heart rate, sleep and gps data without Huawei Backup or root: in Huawei Health go to Account center > Privacy center > Request your data >  select Health app > Send. Within minutes l received an email with download link.
A zip archive has json files, and xlsx files with fields description and some other data.
BTW tp=b-p-m is pace in imperial system.

**Comment by CTHRU** [comment]
Interesting, thank you for pointing this out. The description of the fields is a good find since now it's clear that the speed records for swimming (tp=rs) are in dm/s. In my case, the json for the 'motion path' data is empty (seems like this export relies on data from the tracking device itself, which is in my case a Honor Band 4 (no GPS) but gets its GPS data from the phone. So at first glance it looks like the json files won't be an option in all cases.

**Comment by aricooperdavis** [comment]
Thank you for sharing that, it's an interesting way to get a bit more data out! I don't think I'll try and parse those files here, as it can only be done monthly, and as such is not convenient for most use cases. If you felt like it would be a valuable addition, though, then please feel free to add it! :-)
