### ISSUE TITLE
Reason for timestamp normalization

### ISSUE THREAD

**Issue by tommyblue** [aricooperdavis/Huawei-TCX-Converter#3]
Hi Ari, I was looking at your code and it's not clear to me the meaning of the timestamp normalization you're doing here:
https://github.com/aricooperdavis/Huawei-TCX-Converter/blob/1dea73e6138c9abf1450f43d44a4349e81c7bfe6/Huawei-TCX-Converter.py#L96-L104

Thanks for the explanation! :)

**Comment by aricooperdavis** [comment]
Good question!

If we look at some lines from the example HiTrack file we can see two different ways of representing the unix timestamp:

[`t=1.55173212E12;`](https://github.com/aricooperdavis/Huawei-TCX-Converter/blob/master/Examples/HiTrack_1551732120000155173259000030001#L1)
[`k=1551732125000;`](https://github.com/aricooperdavis/Huawei-TCX-Converter/blob/master/Examples/HiTrack_1551732120000155173259000030001#L240)

If we look at [files from other devices](https://forum.xda-developers.com/smartwatch/huawei-watch/huawei-watch-gt-export-data-health-t3874330) we see another representation:

`t=1.543646826E9;`

We use these timestamps both to order the entries by time (in order to put them in the right order in the TCX file, and to work out the total exercise duration) and also to write to each Trackpoint in the TCX file in the format required by the TCX Schema. As such we need to make sure that all timestamps are represented in the same way before we do that sorting. Reading the above timestamps in as strings would result in timestamps of `1551732120000`, `1551732125000`, and `1543646826` respectively, so how do we convert these different representations to the same format?

The way I went about this was to normalise all of the timestamps so that they end up as a 10 digit number, which equates to a unix timestamp accurate to the nearest second. I chose this so that we didn't add any apparent accuracy where it doesn't exist; 10 digit timestamps seem to be the shortest found in any files that I've seen.

The code that you're asking about is performing this normalisation; it takes the first entry of a given type, determines the order of magnitude (`oom`) of that timestamp, determines the number that we will have to divide the entry by to make it conform to the format we want (`divisor`), and then divides all of the entries of that type by that number.

It's very possible that there's a more pythonic way to achieve this, but this is what I came up with and it seems to work. Feel free to ask for further clarification, or close the request if this makes it clear! 😄

**Comment by tommyblue** [comment]
Ok, I didn't understand because my device (Band 3 Pro) saves timestamps in the `10**9` format, which automatically converts in the correct unix timestamp when casted to int, e.g. `int("1.552381206E9") => 1552381206`.
I think `10**12` are microseconds. Your solution is more generic for sure (works for any representation), although I **hope** Huawei engineers are smart enough to only use seconds or microseconds for unix timestamps 😅 
Thanks for your explanation!

**Comment by aricooperdavis** [comment]
Absolutely, and that's the approach I used until it broke whilst trying to process a file from another device. I hope they do only use those two representations, but I thought that I may as well implement a catch-all solution if I'm going to be checking anyway!

No problem at all, I'm glad it's working for you :)
