### ISSUE TITLE
[ENHANCEMENT]  Support encrypted Huawei Backups with encryption

### ISSUE THREAD

**Issue by rebaserxx** [aricooperdavis/Huawei-TCX-Converter#35]
The latest version of the Huawei Backup App now enforces encryption for created backups which means I am currently unable to convert files

**Comment by CTHRU** [comment]
I noticed it too. The way it looks in my case is that the program is defunct for now. Since the latest version of Huawei Backup (10.0.0.360_OVE) and more importantly Huawei Health (10.0.0.533) I'm not even able to backup the Health app (probably because backup is disabled in the app's properties). I even tried adb backup all to no avail.

How did you manage to get the backup of the Huawei Health **data** (even encrypted) with the latest version?

**Comment by dan1967** [comment]
Yes, backup of health app is restricted, no way to get data without root phone :-(
Backup is disabled is some "system" Huawei app.

But, with backup from Cloud, is possible. Maybe. ( Issue  #19 )
Data in this json tables is same as in hihealth003.db ( Issue  #29  )

Part of json data in key "motionPathData"-"attribute" is same as in HiTrack files.

**Comment by CTHRU** [comment]
Update from my side. I managed to get the data via the method you mentioned in #19 (requires Huawei Cloud to be enabled). Will see if/how/when the program can be adapted/extended to handle the json contents... To be continued. Created a new ticket for this #37 (could not reopen #19)

**Comment by CTHRU** [comment]
Version 3 now supports direct conversion from requested Huawei Health app data (see also #37). I think this is a far more easy method than trying to figure out how to decrypt an encrypted Huawei Backup (if you can even make one using the latest version?). Hope you agree to close this topic.
