### ISSUE TITLE
support for xml from Huawei privacy data

### ISSUE THREAD

**Issue by fedebarabas** [aricooperdavis/Huawei-TCX-Converter#6]
First of all, thank you for making this tool! 

Exporting the tar files did not work for me. I just could not get them to open. So I asked Huawei for my data instead, and I got a bunch of xml files. One of them is called `11-MotionPath.xml`. I processed this one with your TCX-Converter and I got 

```
---- Input File ----
reading: OKAY
processing gps: OKAY
processing heart-rate/cadence: OKAY

---- Details ----
sport: Running
start: 2018-11-18 09:43:40
duration: 05:31:38
distance: 140843864m

---- XML file ----
generating: OKAY
saving: OKAY
validating: FAILED
```

I tried uploading the output to strava and fails with `Improperly formatted data` error message. So I loaded it into mygpsfiles. Here is the [link](https://www.mygpsfiles.com/app/#xtAQJfKX). So it looks almost ok except for the fact that all my (2) tracks are merged (that seems easy enough to fix) and that it seems sometimes the GPS signal was lost and so those diagonal lines happen. What do you think I should try? Running your script with the -f key did not make a difference.

Thanks agan and please let me know how I can help

**Comment by aricooperdavis** [comment]
Hi fedebarabas,

The script isn't designed to take those XML files, but it might be possible to work with them with some fiddling. Would you be able to upload one of those files here for me to have a look at (I'm not sure if the link you gave me to mygpsfiles will allow me to download the raw data)?

I'd also be interested in seeing your .tar files as I've not come across one that can't be opened yet! Did you remember to disable backup encryption when you backed up the app data?

Thanks for your help, this looks like it could be a new feature in the pipeline.

Ari

**Comment by fedebarabas** [comment]
Hi Ari,

I uploaded the xml files and the tar to this [dropbox folder](https://www.dropbox.com/sh/ezpl65eqhrixncj/AAD_T15IZ_p-houqOh30gvsTa?dl=0).

I did not use encryption, I agree it is strange I cannot open it.

Thanks again and let me know how else I can help

**Comment by aricooperdavis** [comment]
That's really interesting - that's definitely an encrypted backup 🤔 Can you outline the steps you took to make the backup?

That XML file looks very promising, I'm sure we can work on getting that into the converter. Can you let me know how many activities you tracked so that I can more easily identify different events in order to process them separately?

I'm half expecting at some point for Huawei to make an update to their Backup app that encrypts app backups even if you choose not to (this is the case when backing up to a computer, in which case the backup is encrypted with a default password). I hope that's not what's happened here with your encrypted app data!

**Comment by fedebarabas** [comment]
Ok, then I think I know what is going on. I did the backup through HiSuite because for some reason my phone is not detecting usb drives connected through an OTG cable. I assumed that creating the tar file from HiSuite would be equivalent as making it in an external drive. It seems like this is not the case. I'll try to find another OTG cable to find out if mine is faulty

**Comment by aricooperdavis** [comment]
There is a way to decrypt those HiSuite backups if you specify the password rather than let it auto-generate one, but it's [academic rather than practical](https://www.sciencedirect.com/science/article/pii/S1742287618304511) at the moment, and I don't have the skill to implement it. I wish someone could though!

I backup to the SD card and move it across from there usually.

**Comment by aricooperdavis** [comment]
It is now possible to extract the data from the Huawei Privacy data.
